package com.github.alexthe666.iceandfire.core;

import com.github.alexthe666.iceandfire.block.*;
import net.minecraft.block.Block;
import net.minecraft.block.SoundType;

public class ModBlocks {
	public static final SoundType SOUND_TYPE_GOLD = IafBlockRegistry.SOUND_TYPE_GOLD;

	public static Block lectern = IafBlockRegistry.lectern;
	public static Block podium = IafBlockRegistry.podium;
	public static Block fire_lily = IafBlockRegistry.fire_lily;
	public static Block frost_lily = IafBlockRegistry.frost_lily;
	public static Block lightning_lily = IafBlockRegistry.lightning_lily;
	public static Block copperPile = IafBlockRegistry.copperPile;
	public static Block goldPile = IafBlockRegistry.goldPile;
	public static Block silverPile = IafBlockRegistry.silverPile;
	public static Block diamondPile = IafBlockRegistry.diamondPile;
	public static Block amethystOre = IafBlockRegistry.amethystOre;
	public static Block copperOre = IafBlockRegistry.copperOre;
	public static Block silverOre = IafBlockRegistry.silverOre;
	public static Block sapphireOre = IafBlockRegistry.sapphireOre;
	public static Block amethystBlock = IafBlockRegistry.amethystBlock;
	public static Block copperBlock = IafBlockRegistry.copperBlock;
	public static Block silverBlock = IafBlockRegistry.silverBlock;
	public static Block sapphireBlock = IafBlockRegistry.sapphireBlock;
	public static Block charedDirt = IafBlockRegistry.charedDirt;
	public static Block charedGrass = IafBlockRegistry.charedGrass;
	public static Block charedStone = IafBlockRegistry.charedStone;
	public static Block charedCobblestone = IafBlockRegistry.charedCobblestone;
	public static Block charedGravel = IafBlockRegistry.charedGravel;
	public static Block charedGrassPath = IafBlockRegistry.charedGrassPath;
	public static Block crackledDirt = IafBlockRegistry.crackledDirt;
	public static Block crackledGrass = IafBlockRegistry.crackledGrass;
	public static Block crackledStone = IafBlockRegistry.crackledStone;
	public static Block crackledCobblestone = IafBlockRegistry.crackledCobblestone;
	public static Block crackledGravel = IafBlockRegistry.crackledGravel;
	public static Block crackledGrassPath = IafBlockRegistry.crackledGrassPath;
	public static Block ash = IafBlockRegistry.ash;
	public static Block frozenDirt = IafBlockRegistry.frozenDirt;
	public static Block frozenGrass = IafBlockRegistry.frozenGrass;
	public static Block frozenStone = IafBlockRegistry.frozenStone;
	public static Block frozenCobblestone = IafBlockRegistry.frozenCobblestone;
	public static Block frozenGravel = IafBlockRegistry.frozenGravel;
	public static Block frozenGrassPath = IafBlockRegistry.frozenGrassPath;
	public static Block frozenSplinters = IafBlockRegistry.frozenSplinters;
	public static Block dragon_ice = IafBlockRegistry.dragon_ice;
	public static Block lightning_stone = IafBlockRegistry.lightning_stone;
	public static Block dragon_ice_spikes = IafBlockRegistry.dragon_ice_spikes;
	public static Block nest = IafBlockRegistry.nest;
	public static Block ancient_dragon_bone_block = IafBlockRegistry.ancient_dragon_bone_block;
	public static Block ancient_dragon_bone_block_wall = IafBlockRegistry.ancient_dragon_bone_block_wall;
	public static Block dragon_bone_block = IafBlockRegistry.dragon_bone_block;
	public static Block dragon_bone_block_wall = IafBlockRegistry.dragon_bone_block_wall;
	public static Block eggInIce = IafBlockRegistry.eggInIce;
	public static Block pixieHouse = IafBlockRegistry.pixieHouse;
	public static Block jar_empty = IafBlockRegistry.jar_empty;
	public static Block jar_pixie = IafBlockRegistry.jar_pixie;
	public static Block myrmex_resin = IafBlockRegistry.myrmex_resin;
	public static Block myrmex_resin_sticky = IafBlockRegistry.myrmex_resin_sticky;
	public static Block desert_myrmex_cocoon = IafBlockRegistry.desert_myrmex_cocoon;
	public static Block jungle_myrmex_cocoon = IafBlockRegistry.jungle_myrmex_cocoon;
	public static Block myrmex_desert_biolight = IafBlockRegistry.myrmex_desert_biolight;
	public static Block myrmex_jungle_biolight = IafBlockRegistry.myrmex_jungle_biolight;
	public static Block myrmex_desert_resin_block = IafBlockRegistry.myrmex_desert_resin_block;
	public static Block myrmex_jungle_resin_block = IafBlockRegistry.myrmex_jungle_resin_block;
	public static Block myrmex_desert_resin_glass = IafBlockRegistry.myrmex_desert_resin_glass;
	public static Block myrmex_jungle_resin_glass = IafBlockRegistry.myrmex_jungle_resin_glass;
	public static Block ghost_chest = IafBlockRegistry.ghost_chest;
	public static BlockDreadBase dread_stone = IafBlockRegistry.dread_stone;
	public static BlockDreadBase dread_stone_bricks = IafBlockRegistry.dread_stone_bricks;
	public static BlockDreadBase dread_stone_bricks_chiseled = IafBlockRegistry.dread_stone_bricks_chiseled;
	public static BlockDreadBase dread_stone_bricks_cracked = IafBlockRegistry.dread_stone_bricks_cracked;
	public static BlockDreadBase dread_stone_bricks_mossy = IafBlockRegistry.dread_stone_bricks_mossy;
	public static BlockDreadBase dread_stone_tile = IafBlockRegistry.dread_stone_tile;
	public static Block dread_stone_face = IafBlockRegistry.dread_stone_face;
	public static Block dread_torch = IafBlockRegistry.dread_torch;
	public static Block dread_stone_bricks_stairs = IafBlockRegistry.dread_stone_bricks_stairs;
	public static BlockGenericSlab dread_stone_bricks_double_slab = IafBlockRegistry.dread_stone_bricks_double_slab;
	public static BlockGenericSlab dread_stone_bricks_slab = IafBlockRegistry.dread_stone_bricks_slab;
	public static Block dread_spawner = IafBlockRegistry.dread_spawner;
	public static Block monster_spawner = IafBlockRegistry.monster_spawner;
}